# Generated by Django 4.0.5 on 2022-09-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('service_starter', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=30)),
                ('requester_email', models.CharField(max_length=50)),
                ('request_date', models.CharField(max_length=30)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_requests.services')),
            ],
        ),
    ]
