# Generated by Django 4.1.1 on 2022-09-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=30)),
                ('requester_email', models.CharField(blank=True, max_length=50, null=True)),
                ('requester_contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_requests.request')),
            ],
        ),
    ]
