# Generated by Django 4.0.5 on 2022-09-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0002_remove_request_request_date_remove_request_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_starter',
        ),
    ]
