# Generated by Django 4.0.3 on 2022-09-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0003_remove_services_service_starter'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requester_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='requester_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
