# Generated by Django 4.1.1 on 2022-09-08 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_asset', models.IntegerField()),
                ('current_asset', models.IntegerField()),
                ('start_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Asset',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tazkira', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=200)),
                ('log_table', models.CharField(max_length=30)),
                ('log_detail', models.TextField()),
                ('log_date', models.CharField(max_length=40)),
                ('logger', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Log',
            },
        ),
        migrations.CreateModel(
            name='Purchase_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('purchasing_date', models.DateField()),
                ('seller', models.CharField(blank=True, max_length=30, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('total_purchase_bill', models.IntegerField()),
                ('purchaser', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roznamcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spender', models.CharField(max_length=30)),
                ('total_spent', models.IntegerField()),
                ('detail', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('sale_date', models.DateField()),
                ('total_sale_bill', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.customer', to_field='name')),
                ('seller', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tazkira', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='Supplier_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('narration', models.CharField(max_length=80)),
                ('transation_date', models.CharField(max_length=80)),
                ('creator_kahatha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.IntegerField(blank=True, null=True)),
                ('item_price', models.IntegerField()),
                ('return_qty', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
                ('sale_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sale_bill')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.IntegerField()),
                ('item_price', models.IntegerField()),
                ('return_qty', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.purchase_bill')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('narration', models.CharField(max_length=80)),
                ('transation_date', models.CharField(max_length=80)),
                ('creator_kahatha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.customer')),
            ],
        ),
    ]
