# Generated by Django 4.0.3 on 2022-06-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_item_amount',
        ),
        migrations.RemoveField(
            model_name='selling',
            name='debit',
        ),
        migrations.AlterField(
            model_name='product',
            name='item_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='selling',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.product', to_field='item_name'),
        ),
        migrations.AlterField(
            model_name='selling',
            name='selling_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='store_purchased',
            name='item_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store_purchased',
            name='purchasing_date',
            field=models.DateField(),
        ),
    ]
