# Generated by Django 4.0.3 on 2022-06-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_remove_product_current_item_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=80)),
                ('narration', models.CharField(max_length=80)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('tran_date', models.CharField(max_length=80)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.customer', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('debit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.IntegerField()),
                ('item_price', models.IntegerField()),
                ('purchasing_date', models.DateField()),
                ('return_qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('pprice', models.IntegerField(blank=True, null=True)),
                ('sprice', models.IntegerField()),
                ('return_qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=5, max_digits=12)),
                ('sale_date', models.DateField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.customer', to_field='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='store_purchased',
            name='item_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='minimum_amount',
            new_name='minimum_requirement',
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Selling',
        ),
        migrations.DeleteModel(
            name='Store_purchased',
        ),
        migrations.AddField(
            model_name='sale_bill',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.product'),
        ),
        migrations.AddField(
            model_name='sale_bill',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sales'),
        ),
        migrations.AddField(
            model_name='purchase_bill',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='bill_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.purchase_bill'),
        ),
    ]
