# Generated by Django 4.0.5 on 2022-08-03 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0003_customer_ledger_purchase_purchase_bill_sale_bill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_kahatha_received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=80)),
                ('narration', models.CharField(max_length=80)),
                ('amount_paid', models.IntegerField()),
                ('payment_date', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=200)),
                ('log_table', models.CharField(max_length=30)),
                ('log_detail', models.TextField()),
                ('log_date', models.CharField(max_length=40)),
                ('logger', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'لوګ',
            },
        ),
        migrations.CreateModel(
            name='Purchase_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.IntegerField()),
                ('item_price', models.IntegerField()),
                ('return_qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.IntegerField(blank=True, null=True)),
                ('item_price', models.IntegerField()),
                ('return_qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'مشتری'},
        ),
        migrations.RenameField(
            model_name='purchase_bill',
            old_name='item_amount',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='purchase_bill',
            old_name='item_price',
            new_name='total_purchase_bill',
        ),
        migrations.RenameField(
            model_name='sale_bill',
            old_name='sprice',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='purchase_bill',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='purchase_bill',
            name='return_qty',
        ),
        migrations.RemoveField(
            model_name='sale_bill',
            name='pprice',
        ),
        migrations.RemoveField(
            model_name='sale_bill',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='sale_bill',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='sale_bill',
            name='return_qty',
        ),
        migrations.RemoveField(
            model_name='sale_bill',
            name='sale_id',
        ),
        migrations.AddField(
            model_name='product',
            name='item_amount_available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_bill',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase_bill',
            name='purchaser',
            field=models.ForeignKey(default=1,max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_bill',
            name='seller',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sale_bill',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.customer', to_field='name'),
        ),
        migrations.AddField(
            model_name='sale_bill',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale_bill',
            name='sale_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 4, 0, 25, 25, 592192)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_bill',
            name='seller',
            field=models.ForeignKey(default=1, max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_bill',
            name='total_sale_bill',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customer_ledger',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.AddField(
            model_name='sales_detail',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.product'),
        ),
        migrations.AddField(
            model_name='sales_detail',
            name='sale_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sale_bill'),
        ),
        migrations.AddField(
            model_name='purchase_detail',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.product'),
        ),
        migrations.AddField(
            model_name='purchase_detail',
            name='purchase_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.purchase_bill'),
        ),
        migrations.AddField(
            model_name='customer_kahatha_received',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.customer'),
        ),
    ]
