# Generated by Django 4.0.5 on 2022-08-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_customer_kahatha_received_log_purchase_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_detail',
            old_name='item_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sales_detail',
            old_name='item_name',
            new_name='product',
        ),
    ]
