# Generated by Django 4.0.5 on 2022-08-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shopapp', '0006_product_column_product_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
        migrations.AlterField(
            model_name='sales_detail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
