# Generated by Django 4.1.1 on 2022-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_replied_to_room_creator_room_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
