# Generated by Django 4.1.1 on 2022-10-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serivce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, unique=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('service_id', models.CharField(max_length=50, unique=True)),
                ('service_incharger', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=None, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubSerivce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('service_id', models.CharField(max_length=50, unique=True)),
                ('service_incharger', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=None, null=True)),
                ('sub_service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.serivce')),
            ],
        ),
    ]
