# Generated by Django 4.1.1 on 2022-10-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_service_id_subserivce_html_id_service_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubSerivce',
            new_name='SubService',
        ),
    ]
