# Generated by Django 4.1.1 on 2022-10-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_subserivce_subservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subservice',
            old_name='sub_service_name',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='service_incharger',
        ),
    ]
