# Generated by Django 4.1.1 on 2022-10-08 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_rename_sub_service_name_subservice_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_incharger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
